### ISSUE TITLE
Allow to customize the systray icon double click behavior

### ISSUE THREAD

**Issue by XtroTheArctic** [xavierfoucrier/inbox-notifier#206] opened 2022-05-13 17:59 UTC
Currently, double clicking the systray icon do a different behavior depending on the number of unread emails:
- no unread email / multiple unread emails: it opens the inbox in the browser
- 1 unread email: it opens the unread email in the browser

It would be nice to have the same behavior every time the systray icon is clicked.

**Comment by xavierfoucrier** [comment] 2022-05-15 22:22
To let other user know, as explained by mail, this is the intended behavior.
I may need some time to think of it.

**Comment by xavierfoucrier** [comment] 2022-07-23 22:42
Unfortunately this won't be implemented.

As explained in the past, the goal of Inbox Notifier is not to offer as many settings / options as possible, but keep things consistent.

**Closed as completed** 2022-07-23 22:42 UTC
Labels: optimization, wontfix

**Comment by XtroTheArctic** [comment] 2022-07-23 23:28
Thank you for your explanation and your great effort on this app.

For me, the "consistent" behavior would be having the same reaction from double clicking the system tray icon regardless of unread email count.

Anyways. I'm maintaining my own fork of this project for my own needs. Thank you very much again for providing this open-source project.
